# Generated by Django 5.2.4 on 2025-07-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='votes',
            field=models.PositiveBigIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
